/**
 * Created by eengoo on 17/3/15.
 */

export const SHOW_OR_HIDE_NEWS_MODAL = 'SHOW_OR_HIDE_NEWS_MODAL';
export const HANDLE_CHANNEL = 'HANDLE_CHANNEL';

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_NULL = "LOGIN_NULL";
export const IS_LOGIN = "IS_LOGIN";

export const FRIENDS_IS_LOADING_MORE = "FRIENDS_IS_LOADING_MORE";
export const FRIENDS_LOADING_ERROR = "FRIENDS_LOADING_ERROR";
export const FRIENDS_LOADING_FINISHED = "FRIENDS_LOADING_FINISHED";
export const FRIENDS_DATA_CONCAT = "FRIENDS_DATA_CONCAT";